[project]
name = "course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"requests",
	"python-frontmatter",
	"openai>=2.0.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
